---
title: "50sites"
author: "Yanlin Ma + Kevin Murgas"
date: "April 13, 2020"
output: word_document
---
Model 3: $$ y_{i,j,k} = \mu + b_j + I_{tumor} * ( \beta_T + c_j + d_k) + \epsilon_i $$
$$ b_j \sim N(0, \sigma_P), \ c_j \sim N(0,\sigma_{PT}),\ d_k \sim N(0, \sigma_T), \ \epsilon_i \sim N(0,\sigma_E)  $$
Stan Chain parameters: \n
warmup=200, iter=2000, chains=4, thin=1 (no thin), adapt_delta=0.999, seed=123 \n
```{r echo=FALSE, include=FALSE}
library(rstan)
library(gtools)
library(ggplot2)
library(bayesplot)
library(knitr)
library(ggpubr)
```
\n Using Relaxed Gamma Priors (x5 variance) \n
```{r echo=FALSE, include=FALSE}
# Kevin's working directory
setwd("/Users/kevinmurgas/Documents/Data+ project/EPIC data")

# Yanlin's working directory
# setwd("D:/DataPlus2017/Data")

# load data
load("myFA_bulkonly.Rdata")

# Extract single site data
site <- function (site_no) {
  # extract CpG site xx to start
  temp <- FullAnnotation[site_no,]
  
  # here we use all patient samples, excluding glands
  #indices <- c(10:14, 16:40,47,48,58,59,73:76,87:96) # if using full data file
  indices <- c(10:57) # if using bulk only data file
  patientLabel <- substr(colnames(temp[indices]), 1, 1)
  patientLabel[10:12] <- "K*"
  sideLabel <- substr(colnames(temp[indices]), 2, 2)
  tissueLabel <- sideLabel
  tissueLabel[!(sideLabel %in% c("N"))] <- "T"   #replace A/B/D/M with T
  tumorIndicator <- 1 * (tissueLabel=="T")
  
  work <- data.frame(
    beta = logit(t(temp[indices])),
    patient = patientLabel,
    tissue = tissueLabel,
    side = sideLabel,
    tInd = tumorIndicator
    )
  colnames(work)[1] <- "beta"
  return(work)
}

# Using Model with TCGA priors (previously model 3)
stanfit_model <- function (dataset) {
  stanDat <- list(
    pID = as.integer(factor(dataset$patient)),
    tInd = dataset$tInd,
    N = nrow(dataset),
    P = nlevels(dataset$patient),
    y = dataset[, 1]
    )
  stanFit <-
    stan(
      fit = emptyFit,
      warmup = 200,
      iter = 2000,
      chains = 4,
      data = stanDat,
      control = list(adapt_delta = 0.999),
      refresh = 0,
      seed=123
    )
  return(stanFit=stanFit)
}

# Plot raw data and fits
fitplot <- function(data,stanFit) {
  # plot beta and fits at this site for all patients, using mean estimates for b and c coefficients
  # first plot data points
  p1 <- ggplot() + geom_point(data = data, aes(x=tInd, y=beta, colour=patient))
  
  # extract coefficients from stan fit
  pats <- as.integer(factor(data$patient))
  nsamp <- length(pats)
  npats <- max(pats)
  sumTemp <- summary(stanFit)$summary
  mu <- sumTemp[1,1] # mean estimate
  betaT <- sumTemp[2,1] # mean
  sampcoefs <- data.frame(pat = pats, b = sumTemp[6+pats], c = sumTemp[6+npats+pats], d = sumTemp[6+2*npats+c(1:nsamp)])
  patcoefs <- data.frame(pat = 1:npats, b = sumTemp[6+1:npats], c = sumTemp[6+npats+1:npats])
  rm(sumTemp)
  # add individual sample estimates
  sampdf <- data.frame(pat = rep(factor(data$patient),2), patg = rep(factor(1:nsamp),2), tInd = c(rep(0,nsamp),rep(1,nsamp)), est = c(sampcoefs$b+mu, (sampcoefs$b+sampcoefs$c++sampcoefs$d+mu+betaT)))
  p1 <- p1 + geom_line(data=sampdf, aes(x=tInd, y=est, colour=pat, group=patg), linetype="dashed", alpha=0.5)
  # add patient mean estimates
  patdf <- data.frame(pat = rep(levels(data$patient),2), tInd = c(rep(0,npats),rep(1,npats)), est = c(patcoefs$b+mu, patcoefs$b+patcoefs$c+mu+betaT))
  p1 <- p1 + geom_line(data=patdf, aes(x=tInd, y=est, colour=pat))
  # add overall mean estimates as black dots
  meandf <- data.frame(tInd = c(0,1), est = c(mu,mu+betaT))
  p1 <- p1 + geom_point(data=meandf, aes(x=tInd, y=est), size=3, alpha=0.7) + geom_line(data=meandf, aes(x=tInd, y=est), size=2, alpha=0.5)
  
  return(p1)
}

# Plot posterior distribution
postplot_mubetaT <- function(stanFit) {
  p2 <- mcmc_areas(
    as.array(stanFit), 
    pars = c("mu","betaT"),
    prob = 0.8, # 80% intervals
    prob_outer = 0.95, 
    point_est = "median"
  )
  return(p2)
}
postplot_sigmas <- function(stanFit) {
  p2 <- mcmc_areas(
    as.array(stanFit), 
    pars = c("sigma_p", "sigma_pt","sigma_t","sigma_e"),
    prob = 0.8, # 80% intervals
    prob_outer = 0.95, 
    point_est = "median"
  )
  return(p2)
}

## CODE
# Randomly choose 50 sites
set.seed(123)
siteInds <- sample(1:866091,50)
nsites <- length(siteInds)

# check for model_TCGApriors.rds, must add to prevent crash
checkFile <- "model_relaxedgamma3.rds"
if (file.exists(checkFile)) {
  file.remove(checkFile)
  print("caught one!") 
}

# create empty fit to use same model compilation throughout
data1<-site(1)
stanDat1 <- list(
  N = nrow(data1),
  P = nlevels(data1$patient),
  pID = as.integer(factor(data1$patient)),
  tInd = data1$tInd,
  y = data1[, 1]
)
emptyFit <- stan(file="model_relaxedgamma3.stan", data = stanDat1, chains = 0)

# inds for extracting data (mean, sem, median, n_eff, Rhat)
mInd <- c(1, 2, 6, 9, 10)
```

```{r echo=FALSE,include=TRUE,error=FALSE,message=FALSE,warning=FALSE,results='asis',fig.keep='all',fig.show='asis',fig.height=2.9,fig.width=5}

ptm <- proc.time()
n_eff_sum<-numeric(6)
for (i in siteInds) {
  # fit model at given site
  data <- site(i)
  stanFit <- stanfit_model(data)
  
  # plot the fit plot (data and fit overlays), and posteriors of sigmas
  p1 <- fitplot(data, stanFit) + ggtitle(paste("Site", i, ": Beta Fits by Patient"))
  p15 <- postplot_mubetaT(stanFit) + ggtitle("Mu/BetaT Posteriors")
  p2 <- postplot_sigmas(stanFit) + ggtitle("Sigma Posteriors")
  p3 <- traceplot(stanFit,pars=c("sigma_p","sigma_pt","sigma_t","sigma_e"),inc_warmup=TRUE,ncol=1,window=c(0,1000)) + theme(axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(),axis.text.y=element_text(angle=45),legend.position="none")
  p4 <- ggarrange(p2,p3,nrow=1,ncol=2)
  print(p1)
  print(p4)
  
  # text output:
  cat(paste("  \nSite ",i,": Parameter posterior summary\n",sep=''))
  
  # take summary values for first 6 params (mu, betaT, sigmas x4) and last param (lp__)
  fitSumm <- summary(stanFit)$summary[c(1:6,97), mInd]
  
  # compute posterior log-ratio: log(sigmaP/sigmaT), take integral>0, mean, median
  posterior <- as.matrix(stanFit,pars=c("sigma_p","sigma_t"))
  logPTratio <- log(posterior[,1]/posterior[,2])
  CpGscore <- c(mean(logPTratio > 0), mean(logPTratio), median(logPTratio))
  fitSumm <- rbind(fitSumm,CpGscore)
  
  # print kable of summary values
  print(kable(fitSumm))
  cat("  \n")
  
  n_eff_sum <- n_eff_sum + fitSumm[,3]
}
mtp <- proc.time() - ptm

```


```{r echo=FALSE,include=TRUE}

print(mtp)
print(paste("Completed run on sites:", paste(siteInds, collapse=" ")))
print(paste("n_eff averages:",paste(round(n_eff_sum/nsites), collapse=" ")))
```