---
title: "StanResultsSummary"
author: "Kevin Murgas"
date: "4/30/2020"
output: pdf_document
---
Summary of Stan Model Fit Results: Full-Scale (850K sites)
\newline Relaxed Gamma priors (using relaxed gamma fits with x3 variance)
```{r Setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggpubr)
library(knitr)
```

```{r Load, echo=FALSE, include=FALSE}
setwd("/Users/kevinmurgas/Documents/Data+ project/EPIC data")
load("myFA_bulkonly.Rdata")
load("FullResultsTCGA_relaxedgamma3.Rdata")

# make a dataframe of the 3 sigma vectors (take median of posterior)
# and do some log transforms
sigma_df <- data.frame(sigmaP=sigmaP_full$p50,sigmaPT=sigmaPT_full$p50,sigmaT=sigmaT_full$p50)
logsig_df <- log(sigma_df)
logRatio_df <- data.frame(PPTr=(logsig_df$sigmaP-logsig_df$sigmaPT),PTr=(logsig_df$sigmaP-logsig_df$sigmaT),PTTr=(logsig_df$sigmaPT-logsig_df$sigmaT))
sigmaMeans <- colMeans(sigma_df)
logsigMeans <- colMeans(logsig_df)
logRatioMeans <- colMeans(logRatio_df)
```

n_eff + Rhat Summary: \newline
```{r Diags, echo=FALSE,include=TRUE,error=FALSE,message=FALSE,warning=FALSE,results='asis',fig.keep='all',fig.show='asis',fig.height=3.5,fig.width=6.5}
library(knitr)
# making matrix of data for each parameter (mu, betaT, sigmaP, sigmaPT, sigmaT, sigmaE, lp__)
# reporting: average n_eff, min n_eff, site of min n_eff, # n_eff<500, (%), # n_eff<100, (%)
n_eff_mat <- matrix(nrow=7, ncol=7)
n_eff_mat[1,] <- c(mean(mu_full$n_eff), min(mu_full$n_eff), which(mu_full$n_eff==min(mu_full$n_eff)), sum(mu_full$n_eff<500), sum(mu_full$n_eff<500)*100/length(mu_full$n_eff), sum(mu_full$n_eff<100), sum(mu_full$n_eff<100)*100/length(mu_full$n_eff))
n_eff_mat[2,] <- c(mean(betaT_full$n_eff), min(betaT_full$n_eff), which(betaT_full$n_eff==min(betaT_full$n_eff)), sum(betaT_full$n_eff<500), sum(betaT_full$n_eff<500)*100/length(betaT_full$n_eff), sum(betaT_full$n_eff<100), sum(betaT_full$n_eff<100)*100/length(betaT_full$n_eff))
n_eff_mat[3,] <- c(mean(sigmaP_full$n_eff), min(sigmaP_full$n_eff), which(sigmaP_full$n_eff==min(sigmaP_full$n_eff)), sum(sigmaP_full$n_eff<500), sum(sigmaP_full$n_eff<500)*100/length(sigmaP_full$n_eff), sum(sigmaP_full$n_eff<100), sum(sigmaP_full$n_eff<100)*100/length(sigmaP_full$n_eff))
n_eff_mat[4,] <- c(mean(sigmaPT_full$n_eff), min(sigmaPT_full$n_eff), which(sigmaPT_full$n_eff==min(sigmaPT_full$n_eff)), sum(sigmaPT_full$n_eff<500), sum(sigmaPT_full$n_eff<500)*100/length(sigmaPT_full$n_eff), sum(sigmaPT_full$n_eff<100), sum(sigmaPT_full$n_eff<100)*100/length(sigmaPT_full$n_eff))
n_eff_mat[5,] <- c(mean(sigmaT_full$n_eff), min(sigmaT_full$n_eff), which(sigmaT_full$n_eff==min(sigmaT_full$n_eff)), sum(sigmaT_full$n_eff<500), sum(sigmaT_full$n_eff<500)*100/length(sigmaT_full$n_eff), sum(sigmaT_full$n_eff<100), sum(sigmaT_full$n_eff<100)*100/length(sigmaT_full$n_eff))
n_eff_mat[6,] <- c(mean(sigmaE_full$n_eff), min(sigmaE_full$n_eff), which(sigmaE_full$n_eff==min(sigmaE_full$n_eff)), sum(sigmaE_full$n_eff<500), sum(sigmaE_full$n_eff<500)*100/length(sigmaE_full$n_eff), sum(sigmaE_full$n_eff<100), sum(sigmaE_full$n_eff<100)*100/length(sigmaE_full$n_eff))
n_eff_mat[7,] <- c(mean(lp_full$n_eff), min(lp_full$n_eff), which(lp_full$n_eff==min(lp_full$n_eff)), sum(lp_full$n_eff<500), sum(lp_full$n_eff<500)*100/length(lp_full$n_eff), sum(lp_full$n_eff<100), sum(lp_full$n_eff<100)*100/length(lp_full$n_eff))
rownames(n_eff_mat)<-c("mu","betaT","sigmaP","sigmaPT","sigmaT","sigmaE","lp__")

kable(n_eff_mat, col.names=c("Avg n_eff", "Min n_eff", "< Site", "# <500","% <500","# <100", "% <100"), digits = 2)

# again for Rhat
Rhat_mat <- matrix(nrow=7, ncol=7)
Rhat_mat[1,] <- c(mean(mu_full$Rhat), max(mu_full$Rhat), which(mu_full$Rhat==max(mu_full$Rhat)), sum(mu_full$Rhat>1.1), sum(mu_full$Rhat>1.1)*100/length(mu_full$Rhat), sum(mu_full$Rhat>1.01), sum(mu_full$Rhat>1.01)*100/length(mu_full$Rhat))
Rhat_mat[2,] <- c(mean(betaT_full$Rhat), max(betaT_full$Rhat), which(betaT_full$Rhat==max(betaT_full$Rhat)), sum(betaT_full$Rhat>1.1), sum(betaT_full$Rhat>1.1)*100/length(betaT_full$Rhat), sum(betaT_full$Rhat>1.01), sum(betaT_full$Rhat>1.01)*100/length(betaT_full$Rhat))
Rhat_mat[3,] <- c(mean(sigmaP_full$Rhat), max(sigmaP_full$Rhat), which(sigmaP_full$Rhat==max(sigmaP_full$Rhat)), sum(sigmaP_full$Rhat>1.1), sum(sigmaP_full$Rhat>1.1)*100/length(sigmaP_full$Rhat), sum(sigmaP_full$Rhat>1.01), sum(sigmaP_full$Rhat>1.01)*100/length(sigmaP_full$Rhat))
Rhat_mat[4,] <- c(mean(sigmaPT_full$Rhat), max(sigmaPT_full$Rhat), which(sigmaPT_full$Rhat==max(sigmaPT_full$Rhat)), sum(sigmaPT_full$Rhat>1.1), sum(sigmaPT_full$Rhat>1.1)*100/length(sigmaPT_full$Rhat), sum(sigmaPT_full$Rhat>1.01), sum(sigmaPT_full$Rhat>1.01)*100/length(sigmaPT_full$Rhat))
Rhat_mat[5,] <- c(mean(sigmaT_full$Rhat), max(sigmaT_full$Rhat), which(sigmaT_full$Rhat==max(sigmaT_full$Rhat)), sum(sigmaT_full$Rhat>1.1), sum(sigmaT_full$Rhat>1.1)*100/length(sigmaT_full$Rhat), sum(sigmaT_full$Rhat>1.01), sum(sigmaT_full$Rhat>1.01)*100/length(sigmaT_full$Rhat))
Rhat_mat[6,] <- c(mean(sigmaE_full$Rhat), max(sigmaE_full$Rhat), which(sigmaE_full$Rhat==max(sigmaE_full$Rhat)), sum(sigmaE_full$Rhat>1.1), sum(sigmaE_full$Rhat>1.1)*100/length(sigmaE_full$Rhat), sum(sigmaE_full$Rhat>1.01), sum(sigmaE_full$Rhat>1.01)*100/length(sigmaE_full$Rhat))
Rhat_mat[7,] <- c(mean(lp_full$Rhat), max(lp_full$Rhat), which(lp_full$Rhat==max(lp_full$Rhat)), sum(lp_full$Rhat>1.1), sum(lp_full$Rhat>1.1)*100/length(lp_full$Rhat), sum(lp_full$Rhat>1.01), sum(lp_full$Rhat>1.01)*100/length(lp_full$Rhat))
rownames(Rhat_mat)<-c("mu","betaT","sigmaP","sigmaPT","sigmaT","sigmaE","lp__")

kable(Rhat_mat, col.names=c("Avg Rhat", "Max Rhat", "< Site", "# >1.1","% >1.1","# >1.01", "% >1.01"), digits = 2)
probsites <- unique(c(n_eff_mat[,3],Rhat_mat[,3]))
print(paste("Problem sites:",paste(probsites,collapse=" ")))
```
\newpage
Parameter Distributions (based on medians of posteriors): \newline
```{r Params, echo=FALSE,include=TRUE,error=FALSE,message=FALSE,warning=FALSE,results='asis',fig.keep='all',fig.show='asis',fig.height=3,fig.width=6.5}

# plot mu,betaT,sigmaE,sigmaP,sigmaPT,sigmaT
fBG <- function(x, a, m1, s1, m2, s2) a*dnorm(x,m1,s1) + (1-a)*dnorm(x,m2,s2)
pM <- ggplot(data.frame(mu=mu_full$p50), aes(x=mu)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle("Mu") + xlim(c(-5,5)) + geom_vline(xintercept=mean(mu_full$p50), linetype="dotted") + theme_bw() + stat_function(fun=function(x) fBG(x,0.3557,-3.0675, 0.75214,1.1290, 1.39197)/0.1906566,geom="line",color="red")
pB <- ggplot(data.frame(betaT=betaT_full$p50), aes(x=betaT)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle("BetaT") + xlim(c(-5,5)) + geom_vline(xintercept=mean(betaT_full$p50), linetype="dotted") + theme_bw() + stat_function(fun=function(x) dcauchy(x,-0.04051, 0.5799)/0.54890,geom="line",color="red")
pE <- ggplot(data.frame(sigmaE=sigmaE_full$p50), aes(x=sigmaE)) + geom_histogram(aes(y=..ncount..), binwidth=0.05) + ggtitle("sigmaE") + xlim(c(0,2)) + geom_vline(xintercept=mean(sigmaE_full$p50), linetype="dotted") + theme_bw() + stat_function(fun=function(x) dgamma(x,2,2)/0.7357589, geom="line",color="red")
pP <- ggplot(sigma_df, aes(x=sigmaP)) + geom_histogram(aes(y=..ncount..), binwidth=0.05) + ggtitle("sigmaP") + xlim(c(0,2)) + geom_vline(xintercept=sigmaMeans[1], linetype="dotted") + theme_bw() + stat_function(fun=function(x) dgamma(x, 2.7693, 7.0029)/2.0046, geom="line",color="red")
pPT <- ggplot(sigma_df, aes(x=sigmaPT)) + geom_histogram(aes(y=..ncount..), binwidth=0.05) + ggtitle("sigmaPT") + xlim(c(0,2)) + geom_vline(xintercept=sigmaMeans[2], linetype="dotted") + theme_bw() + stat_function(fun=function(x) dgamma(x, 2.1457, 2.4819)/0.8615, geom="line",color="red")
pT <- ggplot(sigma_df, aes(x=sigmaT)) + geom_histogram(aes(y=..ncount..), binwidth=0.05) + ggtitle("sigmaT") + xlim(c(0,2)) + geom_vline(xintercept=sigmaMeans[3], linetype="dotted") + theme_bw() + stat_function(fun=function(x) dgamma(x, 3.3643, 10.430)/2.6129, geom="line",color="red")

p6 <- ggarrange(pM,pB,pE,pP,pPT,pT,labels=c("M","B","E","P","PT","T"),hjust=0,nrow=2,ncol=3)
print(p6)
rm(pM,pB,pE,pP,pPT,pT)

# plot the log sigmas
pP <- ggplot(logsig_df, aes(x=sigmaP)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle("log(sigmaP)") + xlim(c(-5,5)) + geom_vline(xintercept=logsigMeans[1], linetype="dotted") + theme_bw()  + stat_function(fun=function(x) dgamma(exp(x), 2.7693, 7.0029)/2.0046, geom="line",color="red")
pPT <- ggplot(logsig_df, aes(x=sigmaPT)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle("log(sigmaPT)") + xlim(c(-5,5)) + geom_vline(xintercept=logsigMeans[2], linetype="dotted") + theme_bw() + stat_function(fun=function(x) dgamma(exp(x), 2.1457, 2.4819)/0.8615, geom="line",color="red")
pT <- ggplot(logsig_df, aes(x=sigmaT)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle("log(sigmaT)") + xlim(c(-5,5)) + geom_vline(xintercept=logsigMeans[3], linetype="dotted") + theme_bw() + stat_function(fun=function(x) dgamma(exp(x), 3.3643, 10.430)/2.6129, geom="line",color="red")
# and log ratios
pPPTr <- ggplot(logRatio_df, aes(x=PPTr)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle(expression("log("*sigma*"P/"*sigma*"PT)")) + xlim(c(-5,5)) + geom_vline(xintercept=logRatioMeans[1], linetype="dotted") + theme_bw()
pPTr <- ggplot(logRatio_df, aes(x=PTr)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle(expression("log("*sigma*"P/"*sigma*"T)")) + xlim(c(-5,5)) + geom_vline(xintercept=logRatioMeans[2], linetype="dotted") + theme_bw()
pPTTr <- ggplot(logRatio_df, aes(x=PTTr)) + geom_histogram(aes(y=..ncount..), binwidth=0.1) + ggtitle(expression("log("*sigma*"PT/"*sigma*"T)")) + xlim(c(-5,5)) + geom_vline(xintercept=logRatioMeans[3], linetype="dotted") + theme_bw()

p6 <- ggarrange(pP,pPT,pT,pPPTr,pPTr,pPTTr,labels=c("logP","logPT","logT","PPTr","PTr","PTTr"),hjust=0,nrow=2,ncol=3)
print(p6)
rm(pPPTr,pPTr,pPTTr,p6)

# density plots of sigmas x sigmas
# too long to load/print with full data! using ~1:10 thinning
logsig_df_thin <- logsig_df
pPxPT <- ggplot(logsig_df_thin, aes(x=sigmaP,y=sigmaPT)) + geom_bin2d(binwidth=c(0.1,0.1), show.legend=FALSE) + ggtitle("log-P vs log-PT") + xlim(-5,2) + ylim(-5,2)
pPxT <- ggplot(logsig_df_thin, aes(x=sigmaP,y=sigmaT)) + geom_bin2d(binwidth=c(0.1,0.1), show.legend=FALSE) + ggtitle("log-P vs log-T") + xlim(-5,2) + ylim(-5,2)
pPTxT <- ggplot(logsig_df_thin, aes(x=sigmaPT,y=sigmaT)) + geom_bin2d(binwidth=c(0.1,0.1), show.legend=FALSE) + ggtitle("log-PT vs log-T") + xlim(-5,2) + ylim(-5,2)
pSxS1 <- ggarrange(pPxT,pPTxT,pPxPT,nrow=2,ncol=2)
logsig_df_thin <- logsig_df[sample(1:dim(logsig_df)[1], 60000, replace=F),]
pPxPT <- ggplot(logsig_df_thin, aes(x=sigmaP,y=sigmaPT)) + geom_density2d() + ggtitle("log-P vs log-PT") + xlim(-3,1) + ylim(-3,1)
pPxT <- ggplot(logsig_df_thin, aes(x=sigmaP,y=sigmaT)) + geom_density2d() + ggtitle("log-P vs log-T") + xlim(-3,1) + ylim(-3,1)
pPTxT <- ggplot(logsig_df_thin, aes(x=sigmaPT,y=sigmaT)) + geom_density2d() + ggtitle("log-PT vs log-T") + xlim(-3,1) + ylim(-3,1)
pSxS2 <- ggarrange(pPxT,pPTxT,pPxPT,nrow=2,ncol=2)
pSxS <- ggarrange(pSxS1,pSxS2,nrow=1,ncol=2)
print(pSxS)
rm(pSxS1,pSxS2)
```
\newpage
Principal Component Analysis (on all sites log-sigma values) \newline
```{r PCA, echo=FALSE,include=TRUE,error=FALSE,message=FALSE,warning=FALSE,results='asis',fig.keep='all',fig.show='asis',fig.height=2.5,fig.width=6.5}
pca <- princomp(logsig_df)
pve <- pca$sdev^2/sum(pca$sdev^2)
summ <- cbind(t(pca$loadings[,]),pve)
colnames(summ)[4] <- "Frac. var explained"
kable(summ,digits=4)

# plot scores of sites along PCA axes
# first just axes 1+2 #geom_bin2d(binwidth=c(0.1,0.1), show.legend=FALSE)
pca_df <- data.frame(pca$scores)
pca_df_thin <- pca_df[sample(1:dim(logsig_df)[1], 60000, replace=F),]
p1<-ggplot(data=pca_df_thin, aes(x=Comp.1, y=Comp.2)) + geom_density2d() + ggtitle("Comp 1 vs 2")
p2<-ggplot(data=pca_df_thin, aes(x=Comp.1, y=Comp.3)) + geom_density2d() + ggtitle("Comp 1 vs 3")
p3<-ggplot(data=pca_df_thin, aes(x=Comp.2, y=Comp.3)) + geom_density2d() + ggtitle("Comp 2 vs 3")
p4<-ggarrange(p1,p2,p3,nrow=1,ncol=3)
print(p4)
```




